drop procedure add_games;
drop procedure add_user;
drop table tbl_gamesLibary;
drop table tbl_games;
drop table tbl_userProfile;

create table tbl_userProfile
(
user_id number generated by default as identity primary key,
username varchar2(250),
emailadress varchar2(250),
passwort varchar2(255)
);

create table tbl_games
(
game_id number generated by default as identity primary key,
titel varchar2(30),
genre varchar2(30),
description VARCHAR2(1000) COLLATE BINARY_CI CONSTRAINT description UNIQUE,
platform varchar(30),
release_date date,
user_id number
);


create table tbl_gamesLibary
(
lib_id number generated by default as identity primary key,
user_id number,
game_id number,
status  number,
review  number
);

alter table tbl_gamesLibary
add constraint fk_user_id
foreign key (user_id)
references tbl_userProfile(user_id);

alter table tbl_gamesLibary
add constraint fk_games_id
foreign key (game_id)
references tbl_games (game_id);

create procedure add_user
(
p_username varchar2,
p_emailadress varchar2,
p_passwort varchar2
)as
begin
insert into tbl_userprofile (username,emailadress,passwort)
values (p_username,p_emailadress,p_passwort);
commit;
end add_user;
/

CREATE OR REPLACE PROCEDURE add_games
(
    p_titel VARCHAR2,
    p_genre VARCHAR2,
    p_description VARCHAR2,
    p_platform VARCHAR2,
    p_release DATE,
    p_user_id number
) AS
BEGIN
    INSERT INTO tbl_games (titel, genre, description, platform, release_date, user_id)
    VALUES (p_titel, p_genre, p_description, p_platform, to_date(p_release,'DD.MM.YYY'),p_user_id );
    
    COMMIT;
END add_games;
/


select * from tbl_userProfile;
select * from tbl_games;

SELECT user_id FROM tbl_userProfile WHERE username = '444' and passwort = '1234' and emailadress ='123@gmail.com'  ;

select * from  tbl_gamesLibary;
